# Generated by Django 4.0.3 on 2023-04-30 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marshmallow', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Marshmallow_User',
        ),
        migrations.AlterField(
            model_name='board',
            name='idx',
            field=models.IntegerField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
