# Generated by Django 4.0.3 on 2023-04-30 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marshmallow', '0002_rename_user_marshmallow_user_alter_board_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='idx',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
