# Generated by Django 4.0.3 on 2023-05-03 01:31

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marshmallow', '0003_alter_board_idx'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='marshmallow_user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='board',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
