# Generated by Django 4.0.3 on 2023-05-09 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marshmallow', '0004_alter_marshmallow_user_managers_board_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='username',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
