# Generated by Django 4.0.3 on 2023-05-10 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marshmallow', '0006_image_remove_board_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='username',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='image',
            name='username',
        ),
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
