# Generated by Django 4.0.3 on 2023-05-21 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marshmallow', '0008_alter_marshmallow_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='marshmallow_user',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
