# Generated by Django 4.0.3 on 2023-05-21 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marshmallow', '0009_alter_board_id_alter_marshmallow_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='hashtag',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
