# Generated by Django 4.0.2 on 2023-05-27 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Marshmallow', '0013_article_delete_board'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='modified_by',
        ),
    ]
