# Generated by Django 4.0.2 on 2023-05-28 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marshmallow', '0014_remove_article_modified_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='modified_at',
            field=models.DateTimeField(null=True),
        ),
    ]
