# Generated by Django 4.0.2 on 2023-06-02 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marshmallow', '0016_alter_article_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='marshmallow_user',
            name='refreshToken',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
