# Generated by Django 4.0.2 on 2023-06-19 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marshmallow', '0018_image_hashtag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marshmallow_user',
            name='refreshToken',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
